app: 
  build: ../../
  dockerfile: docker/release/Dockerfile
  links:
    - db
#  volumes:
#    - /tmp/app-uwsgilogs1:/tmp/app-uwsgilogs1
  volumes_from:
    - webroot
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.release
    MYSQL_HOST: db
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
#    DEBUG: "True"
#    ALLOWED_HOSTS: wahshow
  command:
    - uwsgi 
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todobackend.wsgi"
    - "--master"
    - "--die-on-term"
    - "--logto2 /tmp/app-uwsgilogs1"
  ports:
#    - "8000:8000"  
    - "8001:8000"  

test:
  image: wsoyinka/remindmebackend-specs
  links:
    - nginx
  environment:
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
    JUNIT_REPORT_STACK: 1
  command: --reporter mocha-jenkins-reporter


nginx:
  build: .
  dockerfile: Dockerfile.nginx
  links:
    - app
  volumes_from:
   - webroot
  ports:
    - "8000:8000"  
    - "8002:80"  

webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/todobackend
  entrypoint: "true"

db:
  image: mysql:5.6
  expose: 
    - "3306"
  environment:
    MYSQL_DATABASE: todobackend
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password


agent:
  image: wsoyinka/remindme-docker-ansible
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"  
    PROBE_TIMEOUT: "600"  
  command:
    - "probe.yml"
